### ISSUE TITLE
[suggestion]: add a Theme Switcher 

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#1068]
I think it would be nice to have a Theme Switcher component that looks more like a tradional Theme Switcher then just text. 

To be clear the text in the footer does not have any issue it works totally fine:

![image](https://user-images.githubusercontent.com/46004116/98279722-203b4500-1fbc-11eb-9061-84f9c0786d60.png)

But the hard part is merging the above 4 word long string into the Dashboard Layout.

Maybe it would be more feasible to use something like the following instead if the 4 word long strings:

![image](https://user-images.githubusercontent.com/46004116/98280235-ec145400-1fbc-11eb-94b1-a3f2a186ce56.png)

**Comment by nisarhassan12** [comment]
@shicholas What are your thoughts one this? Thanks

**Comment by shicholas** [comment]
that looks great, it'd be awesome to have.
