### ISSUE TITLE
Header layout does not look good across various screen sizes

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#1069]
Header layout does not look good across various screen sizes. We Must make sure that it looks good across all devices.

![image](https://user-images.githubusercontent.com/46004116/98280831-cb98c980-1fbd-11eb-8728-36e5ab73ee89.png)

![image](https://user-images.githubusercontent.com/46004116/98281027-0864c080-1fbe-11eb-85e7-c176954353e3.png)

I like minimalism and for my taste, there is just too much going on on the small screen area in the top. I know that all the things are important. I was wondering whether we could defer some of the info to either appear down or somewhere else ?

**Comment by shicholas** [comment]
yeah, maybe we should get rid of both buttons at the top and make that a part of the main call button.
