### ISSUE TITLE
When the portal has a lot of vertically spaced content, it goes beyond the screen.

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#1445]
**Describe the bug**
Please watch this video to see the bug:

https://user-images.githubusercontent.com/889427/104104829-55377280-525f-11eb-9b4f-a7b8d61c1e0f.mov

**Expected behavior**
Ideally, the background image and the buffer should always be present in the background.

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/NeonLaw/codebase/pull/1389
