### ISSUE TITLE
Fix Keybindings for Textarea

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#1946]
## Describe the Feature

In our textarea, for instance, /portal/write-rickie, keyboard bindings do not work. Please ensure keybindings like CMD-C on Mac or CTRL-C on Windows work in the editor. Please add tests with Cypress verifying this works.

## Packages

This feature affects

- Web

## For the Assignee

- [ ] Create a branch prefixed `feature/` that solves the issue above.
- [ ] Add this issue to a CHANGELOG file
- [ ] Verify this is deployed on Staging.
- [ ] Verify this is deployed on Production.

**Comment by nisarhassan12** [comment]
@shicholas Is this issue still relevant I tried accessing /portal/write-rickie but I get a 404.

**Comment by shicholas** [comment]
yes, but that website no longer exists, but you can see it here: https://www.neonlaw.com/justice-for-rickie-slaughter/write-rickie

**Comment by nisarhassan12** [comment]
Thanks. Nick, I tried `CMD + A` to select all, `CMD + X` to cut, `CMD + C` for copying and `CMD + V` for pasting and they all seem to work. 

 https://user-images.githubusercontent.com/46004116/119929365-cc636e00-bf96-11eb-857b-8eb2e632b43b.mp4

**Comment by shicholas** [comment]
Please close this issue with a Cypress test
