### ISSUE TITLE
Better homepage stylings on mobile

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#2173]
## Describe the Feature

On mobile the image and text are too big which distract from the search input.

## Packages

This feature affects (delete the unaffected packages below)

- Web

## For the Assignee

- [ ] Create a branch or branches prefixed `feature/` that solves the issue
  above.
- [ ] Add this issue to one or more CHANGELOG files

**Comment by nisarhassan12** [comment]
The current hero area is sort of broken on the Desktop as well. I'll fix that as well within the same PR:

![image](https://user-images.githubusercontent.com/46004116/115131607-c0d56c80-a012-11eb-8f4b-057a443e02e7.png)
