### ISSUE TITLE
Document Template & Question Tables

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#2275]
## Describe the Feature

Both `documentTemplates` and `questions` are public queries at https://api.neonlaw.com/graphiql. Please use those to generate publically available tables, like the ones we have at `/portal/admin/matters`.

Please generate two new pages `/document-templates` and `/questions` which each have the table of GraphQL nodes. 

## Packages

This feature affects (delete the unaffected packages below)

- Web

## For the Assignee

- [ ] Create a branch or branches prefixed `feature/` that solves the issue
  above.
- [ ] Add this issue to one or more CHANGELOG files

**Comment by shicholas** [comment]
@nisarhassan12 does this make sense?

**Comment by nisarhassan12** [comment]
@shicholas Thanks it does. I'll soon make a PR for it.
