### ISSUE TITLE
404 page can be improved 

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#2381]
## Describe the Feature
Currently our 404 does not have the layout as the rest of the site. It is a common pattern over the web that the 404 includes the layout i.e the common public nav and header see Stripe and Slack as as example. 

![image](https://user-images.githubusercontent.com/46004116/118318471-df942980-b512-11eb-89df-dab7342aa34f.png)

## Packages

This feature affects (delete the unaffected packages below)

- [x] Web
- [ ] Server
- [ ] Infrastructure
- [ ] Git Flow
- [ ] Neon NLP
- [ ] Email
- [ ] Documents
- [ ] Postgres

## For the Assignee

- [ ] Create a branch or branches prefixed `feature/` that solves the issue
  above.
- [ ] Add this issue to one or more Milestones corresponding to the next
  versioned release of a package you develop in.

**Comment by shicholas** [comment]
good call, this is a random image from the Next.JS starter I used to startup the website.
