### ISSUE TITLE
Add hook to press Shift or Command + Enter to submit a form

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#273]
Like here on GitHub, when I have a focus on an input element of a form, I should be table to press either `Shift + ENTER` or `CMD + ENTER` to submit the form.

You can use a keydown event as described in https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js to build the form.  We are looking for an example of using the keydown event with a Cypress test that tests that pressing Shift + Enter works.

Please ask any questions you may have for this challenge.

**Comment by nisarhassan12** [comment]
I would like to make a Pr for this in the coming week.

**Comment by nisarhassan12** [comment]
@shicholas To make progress on this I need access to authenticated areas. Any progress on Github Codespaces setup? Thanks
