### ISSUE TITLE
Add a wrapper container to the layout to constraint the width of the site for better readibility.

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#354]
Over the web, it is a common pattern that contents don't stretch all of the available space because that can cause the contents to be not well readable resulting in bad User Experience.

Most popular websites have the width constraint for instance see:

- https://netlify.com
- https://netflix.com
- www.gitpod.io

![image](https://user-images.githubusercontent.com/46004116/86880957-ebe77300-c106-11ea-8c7b-201b5891cfa0.png)

Currently, in many areas of the site especially on Large devices, the contents are not that easier to read as they are too spread.
For instance see the below screenshot, in order for a user to see the date, the eyes have to travel all the way to the right of the screen and the footer links are far too apart.

![image](https://user-images.githubusercontent.com/46004116/86880387-15ec6580-c106-11ea-91db-06c54ec684c6.png)

![image](https://user-images.githubusercontent.com/46004116/86880300-fe14e180-c105-11ea-9ce8-f8df31eb9216.png)

I'll soon make a PR for this with a fix.

**Comment by shicholas** [comment]
sounds good, it'd be nice to have a way to optionally fully extend a `div`. Netlify does this toward the bottom of their page, and I think a lot of headers have this too.

**Comment by nisarhassan12** [comment]
> sounds good, it'd be nice to have a way to optionally fully extend a div. Netlify does this toward the bottom of their page, and I think a lot of headers have this too.

Thanks! @shicholas it definitely makes sense to have a way to do so. I'll make an issue for this which will probably be handled by a separate PR.

**Comment by nisarhassan12** [comment]
Fixed in #454
