### ISSUE TITLE
Have a way to optionally fully extend an element that takes 100% of viewport width inside of <Container />.

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#363]

**Comment by nisarhassan12** [comment]
@shicholas from what I know having an element that takes 100% of `vw` inside of a container is not a simple thing to accomplish. 

Currently, we can only have an element take up a 100% `vw` by having it outside of the `<Container />` wrapper as we are already doing in a few places:

The content section that says "Neon Law in Action" is contained by an element who is not wrapped by a container instead it uses `<Container />` as a child.

![image](https://user-images.githubusercontent.com/46004116/89745171-640cd400-dacb-11ea-8bbd-30b9016d3669.png)

Is this important to be implemented? If so then I can deeply look into how to make it possible. Thanks.

**Comment by shicholas** [comment]
`100%vw` isn't important here, however, I'd like to see a full-width layout for the authenticated pages at `/portal`. Feel free to redesign this page if you think it'll be easier for you.

**Comment by nisarhassan12** [comment]
Thanks. I will make a  PR with the re-design of authenticated pages in the coming days.

**Comment by shicholas** [comment]
https://joshwcomeau.com/css/full-bleed/ is a nice way of achieving this.

**Comment by nisarhassan12** [comment]
@shicholas Thanks for sharing this. I'll try to look into it this week.

**Comment by shicholas** [comment]
closing for #973
