### ISSUE TITLE
production site does not renders the color theme correctly on Firefox.

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#587]
I suspect that the `useColorMode` hook (which maybe uses  [@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) under the hood) tries to switch the theme to dark which does not work correctly in production for some unknown reason. I tried opening the console and there are no errors in there. 

I tried the local version in Firefox which seems to be working correctly. 

Also, the live(production) version of the site on Chrome seems to be working perfectly.

this is how the site looks:
![image](https://user-images.githubusercontent.com/46004116/89117142-f81be180-d4b4-11ea-9d84-c6c44a5bf163.png)

**Comment by shicholas** [comment]
I think this is a bug with Chakra's color theming, where the site doesn't fully register as `light` or `dark` mode. Let's upgrade to Chakra 1.0 soon and see if this fixes it https://github.com/chakra-ui/chakra-ui/issues/892

**Comment by shicholas** [comment]
closing for #776.
