### ISSUE TITLE
Inline Code Styles are off

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#656]
<img width="837" alt="Screen Shot 2020-08-09 at 9 52 15 PM" src="https://user-images.githubusercontent.com/889427/89752805-a06c1000-da8a-11ea-80d0-dc27276f3e34.png">

In the image above, the inline code styles are off.

**Comment by shicholas** [comment]
This is at https://www.neonlaw.com/blog/basic-linux-commands

**Comment by nisarhassan12** [comment]
I'm working on a fix for this.
