### ISSUE TITLE
Blog post list renders twice

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#737]
**Describe the bug**
Blog post list renders twice

https://www.neonlaw.com/blog

**Comment by nisarhassan12** [comment]
Upon running the start tasking after pulling the latest changes from development I'm unable to reproduce this behaviour. Looks like its already fixed but the change is not yet deployed to production.

![image](https://user-images.githubusercontent.com/46004116/91930493-69d88c80-ecfa-11ea-946a-b7f25a54699e.png)

**Comment by shicholas** [comment]
closing because this is now fixed.
