### ISSUE TITLE
yarn add @packagename does not work in pacakages/interface 

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#741]
running `yarn add react-axe` did not work in the `/interface` directory probably becuase of the TypeScript version is not officially supported by @typescript-eslint/typescript-estree.

![image](https://user-images.githubusercontent.com/46004116/91595257-b0d22500-e97c-11ea-8cf0-d8c60f2f56c6.png)

Running `yarn lint` gives a warning that the TypeScript version is not officially supported by @typescript-eslint/typescript-estree.

![image](https://user-images.githubusercontent.com/46004116/91595095-694b9900-e97c-11ea-8f9f-fb175e3e4cf4.png)

While working on https://github.com/NeonLaw/codebase/pull/740 I manually added the package to the `packages/interface/package.json` and then ran `yarn install` from the root.

**Comment by shicholas** [comment]
I would `cd` into `packages/interface` then try `yarn add <dependency_name>` to install something into the `package.json` for the `@neonlaw/interface` project. Does that work?

**Comment by nisarhassan12** [comment]
Thanks, @shicholas I tried `yarn add react-axe` after changing directory to `pacakges/interface` but it does not seem to be working.

![image](https://user-images.githubusercontent.com/46004116/91690963-41c51e00-eb80-11ea-9662-ab9d853f62f1.png)

![image](https://user-images.githubusercontent.com/46004116/91691080-7e911500-eb80-11ea-86e9-b09272f2b4bf.png)
