### ISSUE TITLE
Add Copy-to-Clipboard functionality

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#758]
**Is your feature request related to a problem? Please describe.**
Add `Copy-to-Clipboard` functionality for code snippets.

**Describe the solution you'd like**
On the page https://www.neonlaw.com/pgp, it would be a nice if the user could click a button to copy the text to their clipboard.

**Comment by shicholas** [comment]
@nisarhassan12 can you look into this soon? Please add a Cypress test when submitting a PR.

**Comment by nisarhassan12** [comment]
Thanks. I'll make a Pr for this tomorrow.
