### ISSUE TITLE
Fonts on non-interface websites need a lift.

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#774]
**Describe the bug**
The design of https://www.lawjobresources.com/, https://www.justiceforrickieslaughter.com, and https://www.deleteyourdata.com are messed up since updating to Chakra UI 1.0.0-rc1

**To Reproduce**
Go to above websites.

**Expected behavior**
The fonts should work, and now it looks too thin.

**Screenshots**
Please see website.

**Comment by nisarhassan12** [comment]
I will make a Pr for this with a fix. 

I'm sorry that I have not tested the non `interface` sites while upgrading.

**Comment by shicholas** [comment]
no worries, thanks for looking into it.
