### ISSUE TITLE
After migration to chakra v1 useColorMode hook does not seem to work properly

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#776]
`useColorMode` hook does not seem to work properly i.e on the initial render the border colour which is applied using it does not work i.e the desired `border-color` is not being applied to the Sections as shown below in the screenshot 

![image](https://user-images.githubusercontent.com/46004116/92321292-2f485a00-f042-11ea-85f1-4a3a03bc5058.png)

same is true for the other elements

![image](https://user-images.githubusercontent.com/46004116/92321373-dcbb6d80-f042-11ea-94bf-be0d8a08e30f.png)

Once the theme is switched via the Theme Switcher the `useColorMode` hook seems to work as expected.

**Comment by nisarhassan12** [comment]
@shicholas I have got this response on the issue https://github.com/chakra-ui/chakra-ui/issues/1984#issuecomment-688490475 

Can you look into tailoring the CSP policy to allow the inline script to run becuase the responder in the issue says it will fix the problem? Thanks

**Comment by nisarhassan12** [comment]
The issue is not resolved locally it seems to work well locally but not in production due to CSP policy. @shicholas Any update on that ?  Thanks

**Comment by shicholas** [comment]
let's just remove the CSP plugin, I can push a PR for that

**Comment by nisarhassan12** [comment]
Ok. Thanks.
