### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#797]
**Is your feature request related to a problem? Please describe.**
When I press `Esc` I should see a Keyboard Shortcut menu like on GitHub.

**Describe the solution you'd like**
Copy GitHub's keyboard functionality. Disable the `Esc` when a form element is in `focus`

**Comment by nisarhassan12** [comment]
I would be in favour of using `Shift + ?` for showing up the dialogue box i.e not sure whether it is a standard i.e but it is the way to do so on Twitter, Github and Gmail.

Pressing `?` alone is usually reserved for bringing up the search and `Esc` is usually for closing popups and so on.

@shicholas What do you think what should we go with?

I will make a PR for this.

**Comment by shicholas** [comment]
`shift + ?` is actually correct, let's go with that

**Comment by nisarhassan12** [comment]
Ok. Thanks.
