### ISSUE TITLE
Flash button when selecting it

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#863]
**Is your feature request related to a problem? Please describe.**
On TypeForm, Stripe, and a few other great websites, when you select a button it will flash for a second, giving the user an indication that that button was what he selected.

**Describe the solution you'd like**
Visit https://www.typeform.com/ and try out the form on the homepage. If you check out the multiple choice question or the 1-10 question and select a choice, you will see the button flash momentarily before calling the click handler associated with that `button`.

**Comment by shicholas** [comment]
@nisarhassan12 does this one make sense? IMO it's nice to have for A11Y stuff.

**Comment by nisarhassan12** [comment]
Yeah. It makes sense. It's a nice thing to have for better user experience and accessibility for those buttons who are selectable.
