### ISSUE TITLE
support CMD+Enter instead of Shift+Enter when submitting a form on Apple devices.

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/codebase#901]
**Is your feature request related to a problem? Please describe.**
On Apple devices submitting a form should be done with the `CMD`+`Enter` key combination.

**Comment by nisarhassan12** [comment]
closing this as it seems to be fixed in https://github.com/NeonLaw/codebase/commit/473b2a7b7bc86ff023cbacb827e59b66c1e0d371.

**Comment by shicholas** [comment]
true, I hope to also add this to all other form inputs for OS X devices.

**Comment by nisarhassan12** [comment]
Sorry I may have misunderstood you. Currently we're only having the `submitOnShiftEnter` wired on Text Areas as `Enter` alone when pressed within an `<input />` triggers the submit event by default on Linux on both Chrome and Firefox. Is the behaviour different on OS X devices or did you meant something else ? Thanks

**Comment by shicholas** [comment]
No problem. For OS X devices I'd like to replace every `submitOnShiftEnter` with `submitOnMetaEnter`.

**Comment by nisarhassan12** [comment]
Yeah make's sense. I'll make a Pr for this.
