### ISSUE TITLE
Export fonts as part of @neonlaw/shared-ui

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#903]
**Is your feature request related to a problem? Please describe.**
By having an export via JavaScript we can remove `cp -vr ./shared-ui/fonts ./interface/fonts`, which are instructions in each of the four Gatsby apps.

**Describe the solution you'd like**
A way to import fonts and their CSS files so we don't need to run `cp` anymore.

**Comment by nisarhassan12** [comment]
@shicholas I'm unable to figure this out. Can you outline how the export is gonna be wired via JS?

**Comment by nisarhassan12** [comment]
This looks relevant https://github.com/fontsource/fontsource
